### ISSUE TITLE
button on wire mngr to re-color all existing wires based on settings.

### ISSUE THREAD

**Issue by jph-wacheski** [david-c14/SubmarineUtility#15]
I really like being able to set colors on wires (standard ones hurt my mind),. however when adding wire mnrg to an existing patch or after changing the color settings it would be good to "refresh all wires".

**Comment by david-c14** [comment]
This has finally been added to the Wire Manager.

Note that the Wire Manager is no longer in this plugin, but can be found in the SubmarineFree plugin as the WM-101.  The main menu options now include an item to 'Recolor All Wires' which will apply the coloring rules to every cable currently in the rack.

WM-101 is due to be published in version 1.0.2 of the SubmarineFree plugin within a few days
